version: '3.7'
services:
  django_gunicorn:
    volumes:
      - static:/static
    build:
      context: ./django
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - ./media:/media
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static:
